name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Install, Lint, and Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # built-in npm cache support

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        # keep this step; ensures consistent formatting on CI
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Run tests
        env:
          CI: true
        run: npm test
